# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='reply',
            name='up_vote',
            field=models.SmallIntegerField(default=0),
        ),
    ]
